ALTER TABLE `competition`
  ADD COLUMN `delivery_method` varchar(32) NOT NULL DEFAULT 'BOTH' COMMENT '送样方式：EXPRESS/ONSITE/BOTH' AFTER `style_library_version`,
  ADD COLUMN `sample_arrival_start` datetime NULL DEFAULT NULL COMMENT '建议送达开始时间' AFTER `delivery_method`,
  ADD COLUMN `sample_arrival_deadline` datetime NULL DEFAULT NULL COMMENT '建议送达截止时间' AFTER `sample_arrival_start`,
  ADD COLUMN `sample_quantity_note` varchar(255) NULL DEFAULT NULL COMMENT '酒样数量要求' AFTER `sample_arrival_deadline`,
  ADD COLUMN `delivery_recipient` varchar(64) NULL DEFAULT NULL COMMENT '收件人' AFTER `sample_quantity_note`,
  ADD COLUMN `delivery_phone` varchar(64) NULL DEFAULT NULL COMMENT '收件联系电话' AFTER `delivery_recipient`,
  ADD COLUMN `delivery_address` varchar(500) NULL DEFAULT NULL COMMENT '收件地址' AFTER `delivery_phone`,
  ADD COLUMN `delivery_note` varchar(1000) NULL DEFAULT NULL COMMENT '送样说明' AFTER `delivery_address`,
  ADD COLUMN `venue_name` varchar(128) NULL DEFAULT NULL COMMENT '比赛场地名称' AFTER `delivery_note`,
  ADD COLUMN `venue_address` varchar(500) NULL DEFAULT NULL COMMENT '比赛场地地址' AFTER `venue_name`,
  ADD COLUMN `venue_time_note` varchar(255) NULL DEFAULT NULL COMMENT '现场时间说明' AFTER `venue_address`,
  ADD COLUMN `venue_contact` varchar(128) NULL DEFAULT NULL COMMENT '现场联系人' AFTER `venue_time_note`,
  ADD COLUMN `venue_map_url` varchar(500) NULL DEFAULT NULL COMMENT '地图链接' AFTER `venue_contact`,
  ADD COLUMN `logistics_visibility` varchar(32) NOT NULL DEFAULT 'PAYMENT_CONFIRMED' COMMENT '物流信息展示规则：PUBLIC/LOGIN_REQUIRED/PAYMENT_CONFIRMED' AFTER `venue_map_url`;
