CREATE TABLE IF NOT EXISTS `award_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `competition_id` bigint NOT NULL,
  `category_id` bigint NULL DEFAULT NULL,
  `category_key` bigint GENERATED ALWAYS AS (coalesce(`category_id`, 0)) STORED,
  `award_type` varchar(32) NOT NULL,
  `award_name` varchar(64) NOT NULL,
  `rank_no` int NULL DEFAULT NULL,
  `enabled_flag` tinyint NOT NULL DEFAULT 1,
  `sort_order` int NOT NULL DEFAULT 0,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_award_rule_slot` (`competition_id`, `category_key`, `award_type`, `rank_no`),
  KEY `idx_award_rule_competition` (`competition_id`),
  KEY `idx_award_rule_category` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Award rules';

CREATE TABLE IF NOT EXISTS `award_result` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `competition_id` bigint NOT NULL,
  `category_id` bigint NULL DEFAULT NULL,
  `category_key` bigint GENERATED ALWAYS AS (coalesce(`category_id`, 0)) STORED,
  `beer_entry_id` bigint NOT NULL,
  `award_rule_id` bigint NULL DEFAULT NULL,
  `award_type` varchar(32) NOT NULL,
  `award_name` varchar(64) NOT NULL,
  `rank_no` int NULL DEFAULT NULL,
  `source_round_id` bigint NULL DEFAULT NULL,
  `source_round_table_id` bigint NULL DEFAULT NULL,
  `source_result_id` bigint NULL DEFAULT NULL,
  `champion_flag` tinyint NOT NULL DEFAULT 0,
  `confirmed_by` bigint NULL DEFAULT NULL,
  `confirmed_time` datetime NULL DEFAULT NULL,
  `published_time` datetime NULL DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_award_result_slot` (`competition_id`, `category_key`, `award_type`, `rank_no`, `status`),
  KEY `idx_award_result_entry` (`beer_entry_id`),
  KEY `idx_award_result_competition` (`competition_id`),
  KEY `idx_award_result_source` (`source_result_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Award results';
