SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO style_library (code, name, version, language, source, status, tags_json)
VALUES ('BJCP_2021_CN', 'BJCP 2021 中文标准库', '2021', '中文', 'BJCP', 1, CAST('["报名必填", "支持搜索", "评审可见"]' AS JSON))
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  version = VALUES(version),
  language = VALUES(language),
  source = VALUES(source),
  status = VALUES(status),
  tags_json = VALUES(tags_json),
  update_time = NOW();

SET @bjcp_cn_library_id := (SELECT id FROM style_library WHERE code = 'BJCP_2021_CN');

DELETE FROM style_item WHERE library_id = @bjcp_cn_library_id;
DELETE FROM style_category WHERE library_id = @bjcp_cn_library_id;

INSERT INTO style_category (library_id, name, sort_order) VALUES
(@bjcp_cn_library_id, '1. 标准型美国啤酒', 1),
(@bjcp_cn_library_id, '2. 国际拉格', 2),
(@bjcp_cn_library_id, '3. 捷克拉格', 3),
(@bjcp_cn_library_id, '4. 浅色麦芽型欧洲拉格', 4),
(@bjcp_cn_library_id, '5. 浅色苦味型欧洲啤酒', 5),
(@bjcp_cn_library_id, '6. 琥珀色麦芽型欧洲拉格', 6),
(@bjcp_cn_library_id, '7. 琥珀色苦味型欧洲啤酒', 7),
(@bjcp_cn_library_id, '8. 深色欧洲拉格', 8),
(@bjcp_cn_library_id, '9. 高酒精度欧洲啤酒', 9),
(@bjcp_cn_library_id, '10. 德国小麦啤酒', 10),
(@bjcp_cn_library_id, '11. 英式苦啤', 11),
(@bjcp_cn_library_id, '12. 浅色英联邦啤酒', 12),
(@bjcp_cn_library_id, '13. 棕色英式啤酒', 13),
(@bjcp_cn_library_id, '14. 苏格兰艾尔', 14),
(@bjcp_cn_library_id, '15. 爱尔兰啤酒', 15),
(@bjcp_cn_library_id, '16. 深色英式啤酒', 16),
(@bjcp_cn_library_id, '17. 高酒精度英式艾尔', 17),
(@bjcp_cn_library_id, '18. 浅色美式艾尔', 18),
(@bjcp_cn_library_id, '19. 琥珀色与棕色美式啤酒', 19),
(@bjcp_cn_library_id, '20. 美式波特与世涛', 20),
(@bjcp_cn_library_id, '21. IPA', 21),
(@bjcp_cn_library_id, '22. 高酒精度美式艾尔', 22),
(@bjcp_cn_library_id, '23. 欧洲酸艾尔', 23),
(@bjcp_cn_library_id, '24. 比利时艾尔', 24),
(@bjcp_cn_library_id, '25. 高酒精度比利时艾尔', 25),
(@bjcp_cn_library_id, '26. 修道院艾尔', 26),
(@bjcp_cn_library_id, '27. 历史啤酒', 27),
(@bjcp_cn_library_id, '28. 美式野菌艾尔', 28),
(@bjcp_cn_library_id, '29. 水果啤酒', 29),
(@bjcp_cn_library_id, '30. 香料啤酒', 30),
(@bjcp_cn_library_id, '31. 替代发酵原料啤酒', 31),
(@bjcp_cn_library_id, '32. 烟熏啤酒', 32),
(@bjcp_cn_library_id, '33. 木材啤酒', 33),
(@bjcp_cn_library_id, '34. 特色啤酒', 34);

INSERT INTO style_item (library_id, category_id, name, style_code, description, status, sort_order) VALUES
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '1. 标准型美国啤酒'), '美式淡拉格', '1A', NULL, 1, 1),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '1. 标准型美国啤酒'), '美式拉格', '1B', NULL, 1, 2),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '1. 标准型美国啤酒'), '奶油艾尔', '1C', NULL, 1, 3),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '1. 标准型美国啤酒'), '美式小麦啤酒', '1D', NULL, 1, 4),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '2. 国际拉格'), '国际浅色拉格', '2A', NULL, 1, 5),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '2. 国际拉格'), '国际琥珀色拉格', '2B', NULL, 1, 6),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '2. 国际拉格'), '国际深色拉格', '2C', NULL, 1, 7),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '3. 捷克拉格'), '捷克浅色拉格', '3A', NULL, 1, 8),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '3. 捷克拉格'), '捷克优质浅色拉格', '3B', NULL, 1, 9),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '3. 捷克拉格'), '捷克琥珀色拉格', '3C', NULL, 1, 10),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '3. 捷克拉格'), '捷克深色拉格', '3D', NULL, 1, 11),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '4. 浅色麦芽型欧洲拉格'), '慕尼黑清亮拉格', '4A', NULL, 1, 12),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '4. 浅色麦芽型欧洲拉格'), '节庆啤酒', '4B', NULL, 1, 13),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '4. 浅色麦芽型欧洲拉格'), '清亮博克', '4C', NULL, 1, 14),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '5. 浅色苦味型欧洲啤酒'), '德式低醇啤酒', '5A', NULL, 1, 15),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '5. 浅色苦味型欧洲啤酒'), '科隆啤酒', '5B', NULL, 1, 16),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '5. 浅色苦味型欧洲啤酒'), '德式清亮出口啤酒', '5C', NULL, 1, 17),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '5. 浅色苦味型欧洲啤酒'), '德式皮尔森', '5D', NULL, 1, 18),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '6. 琥珀色麦芽型欧洲拉格'), '三月啤酒', '6A', NULL, 1, 19),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '6. 琥珀色麦芽型欧洲拉格'), '烟熏啤酒', '6B', NULL, 1, 20),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '6. 琥珀色麦芽型欧洲拉格'), '深色博克', '6C', NULL, 1, 21),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '7. 琥珀色苦味型欧洲啤酒'), '维也纳拉格', '7A', NULL, 1, 22),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '7. 琥珀色苦味型欧洲啤酒'), '老啤酒', '7B', NULL, 1, 23),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '8. 深色欧洲拉格'), '慕尼黑深色拉格', '8A', NULL, 1, 24),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '8. 深色欧洲拉格'), '黑啤酒', '8B', NULL, 1, 25),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '9. 高酒精度欧洲啤酒'), '双料博克', '9A', NULL, 1, 26),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '9. 高酒精度欧洲啤酒'), '冰博克', '9B', NULL, 1, 27),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '9. 高酒精度欧洲啤酒'), '波罗的海波特', '9C', NULL, 1, 28),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '10. 德国小麦啤酒'), '德式小麦啤酒', '10A', NULL, 1, 29),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '10. 德国小麦啤酒'), '深色德式小麦啤酒', '10B', NULL, 1, 30),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '10. 德国小麦啤酒'), '小麦博克', '10C', NULL, 1, 31),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '11. 英式苦啤'), '普通苦啤', '11A', NULL, 1, 32),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '11. 英式苦啤'), '优质苦啤', '11B', NULL, 1, 33),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '11. 英式苦啤'), '强烈苦啤', '11C', NULL, 1, 34),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '12. 浅色英联邦啤酒'), '英式金色艾尔', '12A', NULL, 1, 35),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '12. 浅色英联邦啤酒'), '澳大利亚闪亮艾尔', '12B', NULL, 1, 36),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '12. 浅色英联邦啤酒'), '英式 IPA', '12C', NULL, 1, 37),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '13. 棕色英式啤酒'), '深色低酒精艾尔', '13A', NULL, 1, 38),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '13. 棕色英式啤酒'), '英式棕色艾尔', '13B', NULL, 1, 39),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '13. 棕色英式啤酒'), '英式波特', '13C', NULL, 1, 40),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '14. 苏格兰艾尔'), '苏格兰淡艾尔', '14A', NULL, 1, 41),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '14. 苏格兰艾尔'), '苏格兰重艾尔', '14B', NULL, 1, 42),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '14. 苏格兰艾尔'), '苏格兰出口艾尔', '14C', NULL, 1, 43),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '15. 爱尔兰啤酒'), '爱尔兰红艾尔', '15A', NULL, 1, 44),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '15. 爱尔兰啤酒'), '爱尔兰世涛', '15B', NULL, 1, 45),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '15. 爱尔兰啤酒'), '爱尔兰加强世涛', '15C', NULL, 1, 46),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '16. 深色英式啤酒'), '甜世涛', '16A', NULL, 1, 47),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '16. 深色英式啤酒'), '燕麦世涛', '16B', NULL, 1, 48),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '16. 深色英式啤酒'), '热带世涛', '16C', NULL, 1, 49),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '16. 深色英式啤酒'), '外国加强世涛', '16D', NULL, 1, 50),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '17. 高酒精度英式艾尔'), '英式强艾尔', '17A', NULL, 1, 51),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '17. 高酒精度英式艾尔'), '老艾尔', '17B', NULL, 1, 52),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '17. 高酒精度英式艾尔'), '威重艾尔', '17C', NULL, 1, 53),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '17. 高酒精度英式艾尔'), '英式大麦酒', '17D', NULL, 1, 54),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '18. 浅色美式艾尔'), '金色艾尔', '18A', NULL, 1, 55),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '18. 浅色美式艾尔'), '美式浅色艾尔', '18B', NULL, 1, 56),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '19. 琥珀色与棕色美式啤酒'), '美式琥珀艾尔', '19A', NULL, 1, 57),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '19. 琥珀色与棕色美式啤酒'), '加州普通啤酒', '19B', NULL, 1, 58),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '19. 琥珀色与棕色美式啤酒'), '美式棕色艾尔', '19C', NULL, 1, 59),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '20. 美式波特与世涛'), '美式波特', '20A', NULL, 1, 60),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '20. 美式波特与世涛'), '美式世涛', '20B', NULL, 1, 61),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '20. 美式波特与世涛'), '帝国世涛', '20C', NULL, 1, 62),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '21. IPA'), '美式 IPA', '21A', NULL, 1, 63),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '21. IPA'), '特色 IPA', '21B', NULL, 1, 64),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '21. IPA'), '浑浊 IPA', '21C', NULL, 1, 65),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '22. 高酒精度美式艾尔'), '双倍 IPA', '22A', NULL, 1, 66),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '22. 高酒精度美式艾尔'), '美式强艾尔', '22B', NULL, 1, 67),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '22. 高酒精度美式艾尔'), '美式大麦酒', '22C', NULL, 1, 68),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '22. 高酒精度美式艾尔'), '小麦酒', '22D', NULL, 1, 69),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '23. 欧洲酸艾尔'), '柏林酸小麦', '23A', NULL, 1, 70),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '23. 欧洲酸艾尔'), '法兰德斯红艾尔', '23B', NULL, 1, 71),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '23. 欧洲酸艾尔'), '老棕啤酒', '23C', NULL, 1, 72),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '23. 欧洲酸艾尔'), '兰比克', '23D', NULL, 1, 73),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '23. 欧洲酸艾尔'), '贵兹', '23E', NULL, 1, 74),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '23. 欧洲酸艾尔'), '水果兰比克', '23F', NULL, 1, 75),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '23. 欧洲酸艾尔'), '古斯', '23G', NULL, 1, 76),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '24. 比利时艾尔'), '比利时白啤', '24A', NULL, 1, 77),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '24. 比利时艾尔'), '比利时浅色艾尔', '24B', NULL, 1, 78),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '24. 比利时艾尔'), '护卫啤酒', '24C', NULL, 1, 79),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '25. 高酒精度比利时艾尔'), '比利时金色艾尔', '25A', NULL, 1, 80),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '25. 高酒精度比利时艾尔'), '赛松', '25B', NULL, 1, 81),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '25. 高酒精度比利时艾尔'), '比利时金色烈性艾尔', '25C', NULL, 1, 82),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '26. 修道院艾尔'), '比利时单料', '26A', NULL, 1, 83),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '26. 修道院艾尔'), '比利时双料', '26B', NULL, 1, 84),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '26. 修道院艾尔'), '比利时三料', '26C', NULL, 1, 85),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '26. 修道院艾尔'), '比利时深色烈性艾尔', '26D', NULL, 1, 86),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '地窖啤酒', '27A', NULL, 1, 87),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '肯塔基普通啤酒', '27B', NULL, 1, 88),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '利希滕海纳', '27C', NULL, 1, 89),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '伦敦棕色艾尔', '27D', NULL, 1, 90),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '格罗季斯克啤酒', '27E', NULL, 1, 91),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '禁酒令前拉格', '27F', NULL, 1, 92),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '禁酒令前波特', '27G', NULL, 1, 93),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '黑麦啤酒', '27H', NULL, 1, 94),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '27. 历史啤酒'), '萨赫蒂', '27I', NULL, 1, 95),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '28. 美式野菌艾尔'), '布雷特啤酒', '28A', NULL, 1, 96),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '28. 美式野菌艾尔'), '混合发酵酸啤', '28B', NULL, 1, 97),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '28. 美式野菌艾尔'), '野菌特色啤酒', '28C', NULL, 1, 98),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '28. 美式野菌艾尔'), '纯酸啤酒', '28D', NULL, 1, 99),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '29. 水果啤酒'), '水果啤酒', '29A', NULL, 1, 100),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '29. 水果啤酒'), '水果香料啤酒', '29B', NULL, 1, 101),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '29. 水果啤酒'), '特色水果啤酒', '29C', NULL, 1, 102),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '29. 水果啤酒'), '葡萄艾尔', '29D', NULL, 1, 103),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '30. 香料啤酒'), '香料、草本或蔬菜啤酒', '30A', NULL, 1, 104),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '30. 香料啤酒'), '秋季时令啤酒', '30B', NULL, 1, 105),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '30. 香料啤酒'), '冬季时令啤酒', '30C', NULL, 1, 106),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '30. 香料啤酒'), '特色香料啤酒', '30D', NULL, 1, 107),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '31. 替代发酵原料啤酒'), '替代谷物啤酒', '31A', NULL, 1, 108),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '31. 替代发酵原料啤酒'), '替代糖类啤酒', '31B', NULL, 1, 109),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '32. 烟熏啤酒'), '经典风格烟熏啤酒', '32A', NULL, 1, 110),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '32. 烟熏啤酒'), '特色烟熏啤酒', '32B', NULL, 1, 111),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '33. 木材啤酒'), '木材陈酿啤酒', '33A', NULL, 1, 112),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '33. 木材啤酒'), '特色木材陈酿啤酒', '33B', NULL, 1, 113),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '34. 特色啤酒'), '商业特色啤酒', '34A', NULL, 1, 114),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '34. 特色啤酒'), '混合风格啤酒', '34B', NULL, 1, 115),
(@bjcp_cn_library_id, (SELECT id FROM style_category WHERE library_id = @bjcp_cn_library_id AND name = '34. 特色啤酒'), '实验啤酒', '34C', NULL, 1, 116);

COMMIT;
