CREATE TABLE IF NOT EXISTS `entry_refund` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `beer_entry_id` bigint NOT NULL,
  `entry_payment_id` bigint NOT NULL,
  `refund_no` varchar(64) NOT NULL,
  `amount` decimal(10, 2) NOT NULL,
  `status` varchar(32) NOT NULL,
  `reason` varchar(300) NOT NULL,
  `requested_by_portal_id` bigint NULL DEFAULT NULL,
  `requested_time` datetime NOT NULL,
  `processed_by_admin_id` bigint NULL DEFAULT NULL,
  `processed_time` datetime NULL DEFAULT NULL,
  `success_time` datetime NULL DEFAULT NULL,
  `fail_reason` varchar(300) NULL DEFAULT NULL,
  `wechat_refund_id` varchar(64) NULL DEFAULT NULL,
  `out_refund_no` varchar(64) NULL DEFAULT NULL,
  `notify_raw_json` json NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_entry_refund_no` (`refund_no`),
  KEY `idx_entry_refund_entry` (`beer_entry_id`),
  KEY `idx_entry_refund_payment` (`entry_payment_id`),
  KEY `idx_entry_refund_status` (`status`, `requested_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='报名退款记录';
