-- 比赛级评审表现评价。该表保存人工评价和基于已锁定评分轮生成的评语统计快照，不修改评审账号主表。
CREATE TABLE IF NOT EXISTS `competition_judge_evaluation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `competition_id` bigint NOT NULL,
  `judge_account_id` bigint NOT NULL,
  `judgment_level` tinyint DEFAULT NULL,
  `feedback_quality_level` tinyint DEFAULT NULL,
  `rule_execution_level` tinyint DEFAULT NULL,
  `professionalism_level` tinyint DEFAULT NULL,
  `manual_score` decimal(5,1) DEFAULT NULL,
  `comment_total_chars` int NOT NULL DEFAULT 0,
  `comment_average_chars` int NOT NULL DEFAULT 0,
  `comment_record_count` int NOT NULL DEFAULT 0,
  `comment_requirement_ratio` decimal(8,3) NOT NULL DEFAULT 0,
  `comment_percentile` decimal(6,2) DEFAULT NULL,
  `comment_score` decimal(5,1) DEFAULT NULL,
  `task_completed_count` int NOT NULL DEFAULT 0,
  `task_total_count` int NOT NULL DEFAULT 0,
  `completion_rate` decimal(6,2) NOT NULL DEFAULT 0,
  `total_score` decimal(5,1) DEFAULT NULL,
  `excellent_candidate` tinyint NOT NULL DEFAULT 0,
  `evidence` varchar(1000) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'DRAFT',
  `evaluated_by` bigint DEFAULT NULL,
  `evaluated_time` datetime DEFAULT NULL,
  `confirmed_by` bigint DEFAULT NULL,
  `confirmed_time` datetime DEFAULT NULL,
  `version` int NOT NULL DEFAULT 0,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_competition_judge_evaluation` (`competition_id`,`judge_account_id`),
  KEY `idx_judge_evaluation_judge` (`judge_account_id`,`status`),
  KEY `idx_judge_evaluation_competition_score` (`competition_id`,`status`,`total_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='比赛级评审表现评价';
