<template>
  <div class="recruit-page">
    <AdminPageHeader title="裁判招募">
      <template #actions><button class="tool-button primary" type="button" @click="openCreate">发起招募</button></template>
    </AdminPageHeader>
    <section class="toolbar"><input v-model="keyword" placeholder="搜索比赛名称、编号" @keyup.enter="load"><label v-if="canFilterOrganizers" class="organizer-filter" aria-label="主办方筛选"><OfficeBuilding /><select v-model="organizerType" @change="load"><option v-for="option in organizerOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><select v-model="status" @change="load"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="OPEN">招募中</option><option value="CLOSED">已截止</option><option value="ARCHIVED">已归档</option></select><button class="icon-button" type="button" title="刷新" aria-label="刷新" @click="load"><Refresh /></button></section>
<section class="table-card"><div class="table-head"><span>比赛</span><span>状态</span><span>报名时间</span><span>申请情况</span><span>操作</span></div><div v-for="item in items" :key="item.id" class="table-row"><div><strong>{{ item.competitionName }}</strong></div><span :class="['badge', item.status.toLowerCase()]">{{ statusLabel(item.status) }}</span><span class="time-range">{{ fmtHour(item.recruitmentStart) }} - {{ fmtHour(item.recruitmentDeadline) }}</span><span class="application-summary"><b v-if="item.pendingCount" class="pending">待审核 {{ item.pendingCount }}</b><span v-else>待审核 0</span> · 已录用 {{ item.acceptedCount || 0 }} · 共 {{ item.applicationCount || 0 }}</span><div class="actions"><button class="primary" @click="goDetail(item)">{{ item.pendingCount ? '处理报名' : '查看报名' }}</button><button v-if="['DRAFT','OPEN','CLOSED'].includes(item.status)" @click="edit(item)">编辑</button><button v-if="item.status==='DRAFT'" @click="publish(item)">发布</button></div></div><div v-if="!items.length" class="empty">暂无裁判招募</div></section>
    <JudgeRecruitmentEditor v-model="editor" :recruitment="editing" @saved="load" />
  </div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { OfficeBuilding, Refresh } from '@element-plus/icons-vue'
import AdminPageHeader from '@/components/admin/AdminPageHeader.vue'
import JudgeRecruitmentEditor from './components/JudgeRecruitmentEditor.vue'
import { useRouter } from 'vue-router'
import { fetchJudgeRecruitments, publishJudgeRecruitment } from '@/api/admin'
import { ADMIN_TYPES } from '@/config/adminAccess'
import { getAdminType } from '@/utils/auth'
const router=useRouter()
const items=ref([]), keyword=ref(''), status=ref(''), organizerType=ref('PLATFORM'), editor=ref(false), editing=ref(null)
const canFilterOrganizers=computed(()=>getAdminType()===ADMIN_TYPES.PLATFORM_SUPER_ADMIN)
const organizerOptions=[{label:'啤酒事务局',value:'PLATFORM'},{label:'第三方平台',value:'TENANT'},{label:'所有主办方',value:'ALL'}]
const load=async()=>{const params={keyword:keyword.value,status:status.value}; if(canFilterOrganizers.value) params.organizerType=organizerType.value; items.value=await fetchJudgeRecruitments(params)}
onMounted(load)
function openCreate(){editing.value=null;editor.value=true}
function edit(item){editing.value=item;editor.value=true}
async function publish(i){await publishJudgeRecruitment(i.id);await load();ElMessage.success('招募已发布')}
function goDetail(item){router.push(`/admin/judge-recruitments/${item.id}`)}
const fmtHour=v=>v?new Date(v).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false}):'-'; const statusLabel=s=>({DRAFT:'草稿',OPEN:'招募中',CLOSED:'已截止',ARCHIVED:'已归档'}[s]||s)
</script>
<style scoped>
.tool-button{min-height:42px;padding:0 12px;color:var(--text,#e6edf0);border:1px solid var(--line,rgba(219,232,237,.16));border-radius:8px;background:rgba(255,255,255,.035)}.tool-button.primary{color:var(--gold-soft,#f7d774);border-color:rgba(216,169,53,.32);background:rgba(216,169,53,.08)}
.toolbar .icon-button{margin-left:auto;display:inline-grid;place-items:center;width:42px;min-height:42px;padding:0;color:var(--text,#e6edf0);border:1px solid var(--line,rgba(219,232,237,.16));border-radius:8px;background:rgba(255,255,255,.035);cursor:pointer}
.toolbar .icon-button:hover{color:var(--gold-soft,#f7d774);border-color:rgba(216,169,53,.32);background:rgba(216,169,53,.08)}
.toolbar .icon-button svg{width:17px;height:17px}
.recruit-page{height:100%;padding:0 28px 18px;color:#e6edf0;background:linear-gradient(135deg,#0d1418,#111c20);overflow:auto}.toolbar,.table-card{margin-top:18px;padding:14px;border:1px solid rgba(219,232,237,.1);border-radius:8px;background:rgba(22,32,36,.9)}.toolbar{display:flex;gap:10px;align-items:center}.toolbar input,.toolbar select,.dialog input,.dialog select,.dialog textarea{min-height:40px;border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:8px 10px;color:#e6edf0;background:#101a1e}.toolbar input{width:320px}.organizer-filter{display:flex;align-items:center;gap:6px}.organizer-filter svg{width:15px;color:#e0b84a}.table-head,.table-row{display:grid;grid-template-columns:1.35fr .7fr 1.1fr 1fr 1fr 1.2fr;gap:12px;align-items:center}.table-head{padding:0 10px 10px;color:#8da1aa;font-size:13px}.table-row{padding:13px 10px;border-top:1px solid rgba(219,232,237,.08)}small{display:block;margin-top:4px;color:#8da1aa}.badge{width:max-content;padding:6px 9px;border-radius:7px}.badge.open{color:#6fcf7a;background:#183523}.badge.draft{color:#f7d774;background:#3a3218}.badge.closed,.badge.archived{color:#aab7bd;background:#283238}.actions{display:flex;gap:6px;flex-wrap:wrap}.actions button,.app-row button,.dialog footer button,.dialog header button{border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:7px 10px;color:#e6edf0;background:rgba(255,255,255,.04)}.primary{color:#f7d774!important;border-color:rgba(216,169,53,.3)!important;background:rgba(216,169,53,.1)!important}.mask{position:fixed;inset:0;z-index:10;display:grid;place-items:center;background:rgba(3,8,10,.72)}.dialog{width:min(560px,92vw);max-height:90vh;overflow:auto;padding:22px;border:1px solid rgba(219,232,237,.16);border-radius:8px;background:#162024}.dialog.wide{width:min(760px,92vw)}.dialog label{display:grid;gap:6px;margin-top:13px;color:#a9bbc2;font-size:13px}.dialog textarea{min-height:72px}.dialog footer{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.dialog header{display:flex;justify-content:space-between}.app-row{display:grid;grid-template-columns:1fr auto auto auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid rgba(219,232,237,.08)}.app-row .ok{color:#6fcf7a}.app-row .danger{color:#ffb4a8}.empty{text-align:center;padding:50px;color:#8da1aa}
.dialog::-webkit-scrollbar{width:10px}.dialog::-webkit-scrollbar-track{background:rgba(255,255,255,.025)}.dialog::-webkit-scrollbar-thumb{border:2px solid #162024;border-radius:999px;background:rgba(216,169,53,.3)}.dialog::-webkit-scrollbar-thumb:hover{background:rgba(216,169,53,.5)}.competition-picker{position:relative}.competition-picker input{width:100%;padding-right:34px}.picker-clear{position:absolute;right:8px;top:7px;border:0;background:transparent;color:#8da1aa;font-size:20px}.picker-options{position:absolute;left:0;right:0;top:46px;z-index:2;display:grid;max-height:180px;overflow:auto;border:1px solid rgba(219,232,237,.18);border-radius:7px;background:#162024;box-shadow:0 12px 24px #0005}.picker-options button{padding:10px 12px;border:0;color:#e6edf0;background:transparent;text-align:left}.picker-options button:hover{background:rgba(216,169,53,.1)}.picker-options span{padding:12px;color:#8da1aa}.competition-meta{display:flex;gap:12px;flex-wrap:wrap;margin-top:10px;color:#8da1aa;font-size:12px}.readonly-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.stepper{display:grid;grid-template-columns:40px 1fr 40px;gap:6px}.stepper button{border:1px solid rgba(216,169,53,.28);border-radius:7px;color:#f7d774;background:rgba(216,169,53,.08);font-size:20px}.stepper input{text-align:center}.dialog input[readonly]{color:#8da1aa;background:#0c1519}
.table-head,.table-row{grid-template-columns:minmax(240px,1.6fr) 100px minmax(300px,1.4fr) minmax(260px,1.5fr) minmax(210px,1.2fr)}.time-range,.application-summary{white-space:nowrap}.table-row strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
</style>
