<template>
  <div class="detail-page">
    <AdminPageHeader :title="recruitment?.competitionName || '裁判招募详情'">
      <template #actions><button class="tool-button" type="button" @click="router.back()">返回</button></template>
    </AdminPageHeader>
    <div v-if="recruitment" class="summary"><span>{{ statusLabel(recruitment.status) }}</span><span>{{ recruitment.venue || '-' }}</span><span>{{ fmt(recruitment.recruitmentDeadline) }} 截止</span><div class="summary-actions"><button v-if="recruitment.status==='OPEN'" class="tool-button" type="button" @click="changeRecruitment('close')">截止报名</button><button v-if="recruitment.status==='CLOSED'" class="tool-button primary" type="button" @click="changeRecruitment('reopen')">再开放</button></div></div>
    <section class="panel"><div class="panel-head"><h2>报名裁判</h2><div class="filters"><select v-model="appStatus" @change="loadApps"><option value="">全部</option><option value="APPLIED">待审核</option><option value="ACCEPTED">已录用</option><option value="REJECTED">不录用</option><option value="WITHDRAWN">已撤回</option></select></div></div>
      <div class="app-head"><span>裁判</span><span>资质</span><span>报名信息</span><span>评委评分</span><span>状态</span><span>操作</span></div>
      <div v-for="a in sortedApps" :key="a.id" class="app-row"><span class="identity"><strong>{{ a.judgeName || '未填写姓名' }}</strong></span><span class="qualification">{{ a.qualification || '未填写资质' }}</span><span class="note">{{ a.note || '-' }}</span><span class="judge-score" :title="scoreTitle(a)"><template v-if="a.judgeScoreCompetitionCount"><strong>{{ fmtScore(a.judgeScoreAverage) }}</strong><small>{{ a.judgeScoreCompetitionCount }} 场已评</small></template><span v-else class="judge-score-empty">暂无评价</span></span><span class="status">{{ appLabel(a.status) }}</span><div class="row-actions"><button class="tool-button" type="button" @click="selected=a">详情</button><button v-if="a.status==='APPLIED'" class="ok" @click="review(a,'ACCEPTED')">录用</button><button v-if="a.status==='APPLIED'" class="danger" @click="review(a,'REJECTED')">不录用</button><button v-if="['ACCEPTED','REJECTED'].includes(a.status)" class="tool-button" type="button" @click="openStatusEditor(a)">操作</button></div></div>
      <div v-if="!apps.length" class="empty">暂无报名</div>
    </section>
    <aside v-if="selected" class="drawer"><header><h2>{{ selected.judgeName || '裁判详情' }}</h2><button type="button" @click="selected=null">×</button></header><p><b>资质</b>{{ selected.qualification || '-' }}</p><p><b>利益冲突</b>{{ selected.breweryConflictText || (selected.breweryConflictFlag ? '有' : '-') }}</p><p><b>报名备注</b>{{ selected.note || '-' }}</p><p><b>评委评分</b>{{ scoreText(selected) }}</p></aside>
    <div v-if="statusEditor" class="status-mask"><section class="status-dialog"><header><h2>修改状态</h2><button type="button" @click="statusEditor=null">×</button></header><label>状态<select v-model="statusValue"><option value="ACCEPTED">录用</option><option value="REJECTED">不录用</option></select></label><footer><button class="tool-button" type="button" @click="statusEditor=null">取消</button><button class="tool-button primary" type="button" @click="saveStatus">保存</button></footer></section></div>
  </div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import AdminPageHeader from '@/components/admin/AdminPageHeader.vue'
import request from '@/api/request'
import { fetchJudgeRecruitment, fetchJudgeRecruitmentApplications, reviewJudgeRecruitmentApplication } from '@/api/admin'
const route=useRoute(), router=useRouter(), recruitment=ref(null), apps=ref([]), selected=ref(null), appStatus=ref(''), statusEditor=ref(null), statusValue=ref('ACCEPTED')
const sortedApps = computed(() => [...apps.value].sort((a, b) => (a.status === 'APPLIED' ? 0 : 1) - (b.status === 'APPLIED' ? 0 : 1)))
const load=async()=>{recruitment.value=await fetchJudgeRecruitment(route.params.id);await loadApps()}
const loadApps=async()=>{apps.value=await fetchJudgeRecruitmentApplications(route.params.id,{status:appStatus.value})}
const review=async(a,status)=>{await ElMessageBox.confirm(`确认${status==='ACCEPTED'?'录用':'不录用'}${a.judgeName||'该裁判'}吗？`);await reviewJudgeRecruitmentApplication(a.id,{status});await loadApps();ElMessage.success('已处理')}
const openStatusEditor=(a)=>{statusEditor.value=a;statusValue.value=a.status==='ACCEPTED'?'REJECTED':'ACCEPTED'}
const saveStatus=async()=>{const a=statusEditor.value;if(!a)return;await ElMessageBox.confirm(`确认${statusValue.value==='ACCEPTED'?'录用':'不录用'}${a.judgeName||'该裁判'}吗？`);await reviewJudgeRecruitmentApplication(a.id,{status:statusValue.value});statusEditor.value=null;await loadApps();ElMessage.success('已处理')}
const changeRecruitment=async(action)=>{const reopen=action==='reopen';await ElMessageBox.confirm(`确认${reopen?'再开放':'截止'}报名吗？`);await request.post(`/api/admin/judge-recruitments/${route.params.id}/${reopen?'reopen':'close'}`,{}, { authScope:'admin' });await load();ElMessage.success(reopen?'已再开放':'已截止')}
onMounted(load)
const fmt=v=>v?new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'-'
const statusLabel=s=>({DRAFT:'草稿',OPEN:'招募中',CLOSED:'已截止',ARCHIVED:'已归档'}[s]||s)
const appLabel=s=>({APPLIED:'待审核',ACCEPTED:'已录用',REJECTED:'不录用',WITHDRAWN:'已撤回'}[s]||s)
const fmtScore=v=>v==null?'-':Number(v).toFixed(1)
const scoreText=a=>a.judgeScoreCompetitionCount?`${fmtScore(a.judgeScoreAverage)} 平均分 · ${a.judgeScoreCompetitionCount} 场已评${a.judgeScoreLatestCompetition?` · 最近 ${a.judgeScoreLatestCompetition} ${fmtScore(a.judgeScoreLatest)}`:''}`:'暂无赛事评价'
const scoreTitle=a=>a.judgeScoreCompetitionCount&&a.judgeScoreLatestCompetition?`最近：${a.judgeScoreLatestCompetition} ${fmtScore(a.judgeScoreLatest)}`:''
</script>
<style scoped>
.tool-button{min-height:42px;padding:0 12px;color:var(--text,#e6edf0);border:1px solid var(--line,rgba(219,232,237,.16));border-radius:8px;background:rgba(255,255,255,.035)}.tool-button.primary{color:var(--gold-soft,#f7d774);border-color:rgba(216,169,53,.32);background:rgba(216,169,53,.08)}
.qualification,.note{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#a9bbc2}.status{white-space:nowrap}
.detail-page{height:100%;padding:0 28px 18px;color:#e6edf0;background:linear-gradient(135deg,#0d1418,#111c20);overflow:auto}.summary,.panel{margin-top:18px;padding:16px;border:1px solid rgba(219,232,237,.1);border-radius:8px;background:rgba(22,32,36,.9)}.summary{display:flex;gap:24px;align-items:center;color:#a9bbc2}.summary-actions{margin-left:auto;display:flex;gap:8px}.summary-actions button{border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:7px 10px;background:rgba(255,255,255,.04)}.panel-head{display:flex;justify-content:space-between;align-items:center}.panel h2{margin:0;font-size:18px}.filters select{min-height:38px;border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:7px 10px;color:#e6edf0;background:#101a1e}.app-row{display:grid;gap:16px;align-items:center;padding:13px 0;border-top:1px solid rgba(219,232,237,.08)}.identity{border:0;text-align:left;color:#e6edf0;background:transparent;cursor:pointer}.identity small{display:block;margin-top:4px;color:#8da1aa}.row-actions{display:flex;gap:8px}.row-actions button{border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:7px 10px;background:rgba(255,255,255,.04)}.ok{color:#6fcf7a}.danger{color:#ffb4a8}.primary{color:#f7d774}.empty{text-align:center;padding:48px;color:#8da1aa}.drawer{position:fixed;top:0;right:0;width:min(390px,90vw);height:100vh;padding:24px;border-left:1px solid rgba(219,232,237,.14);background:#162024;box-shadow:-14px 0 30px #0005;z-index:5}.drawer header{display:flex;justify-content:space-between;align-items:center}.drawer header button{border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:7px 11px;color:#e6edf0;background:transparent}.drawer p{display:grid;gap:6px;margin:22px 0;color:#d2dde1}.drawer b{color:#8da1aa;font-size:12px;font-weight:400}
.app-row{min-width:0}.identity,.qualification,.note,.status,.judge-score{min-width:0}.identity strong,.qualification,.note{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.app-head{display:grid;grid-template-columns:minmax(140px,.9fr) minmax(160px,1fr) minmax(220px,1.5fr) 128px 80px 190px;gap:16px;padding:14px 0 8px;color:#8da1aa;font-size:13px}.app-row{grid-template-columns:minmax(140px,.9fr) minmax(160px,1fr) minmax(220px,1.5fr) 128px 80px 190px}.app-head span:last-child{text-align:left}.row-actions{display:flex;gap:8px;white-space:nowrap}
.judge-score{display:grid;gap:4px;align-content:center;justify-items:start}.judge-score strong{color:#f7d774;font-size:16px;font-variant-numeric:tabular-nums}.judge-score small{color:#8da1aa;font-size:12px;white-space:nowrap}.judge-score-empty{color:#71868e;font-size:12px}
.status-mask{position:fixed;inset:0;z-index:10;display:grid;place-items:center;background:rgba(3,8,10,.72)}.status-dialog{width:min(360px,90vw);padding:22px;border:1px solid rgba(219,232,237,.16);border-radius:8px;background:#162024}.status-dialog header{display:flex;justify-content:space-between;align-items:center}.status-dialog header button{border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:7px 11px;color:#e6edf0;background:transparent}.status-dialog label{display:grid;gap:6px;margin-top:18px;color:#a9bbc2;font-size:13px}.status-dialog select{min-height:40px;border:1px solid rgba(219,232,237,.16);border-radius:7px;padding:8px 10px;color:#e6edf0;background:#101a1e}.status-dialog footer{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}
</style>
