export const breweryProfile = {
  breweryName: '山雾麦芽工坊',
  contactName: '林启航',
  phone: '13800000001',
  wechat: 'mistmalt_lab',
  city: '广东 深圳',
  address: '南山区蛇口街道海湾路 18 号',
  bio: '专注小批量 IPA、赛季果酸和木桶熟成实验，年产量 420 吨。',
}

export const competitions = [
  {
    id: 'bc-2026',
    name: '2026 Greater Bay Craft Beer Awards',
    shortName: 'BC-2026',
    status: 'REGISTRATION_OPEN',
    stage: '报名中',
    date: '2026-08-18',
    registrationDeadline: '2026-07-20 18:00',
    entryFee: 199,
    venue: '深圳蛇口价值工厂',
    city: '广东 深圳',
    organizer: '大湾区精酿协会',
    description: '面向大湾区精酿厂牌的年度综合赛事，覆盖 IPA、酸啤、深色烈性、拉格与农舍等投递组别。',
    audience: '适合提交稳定量产款、年度代表作和具备清晰风格表达的实验批次。',
    sampleRequirement: '每款酒请准备 4 瓶或 4 罐，单瓶/罐容量建议不低于 330ml。',
    sampleDeadline: '2026-08-01 18:00',
    sampleAddress: '广东省深圳市南山区蛇口街道价值工厂赛事收样处',
    awardNote: '按投递组别评出金、银、铜奖，结果发布后可查看评分反馈、桌长评语和奖状入口。',
    categories: ['美式 IPA', '果味酸啤', '深色烈性啤酒', '拉格', '赛松 / 农舍'],
    styleOptions: ['West Coast IPA', 'Hazy IPA', 'Gose', 'Imperial Stout', 'Munich Helles', 'Saison'],
    entryFields: [
      {
        fieldKey: 'specialIngredients',
        fieldLabel: '特殊工艺',
        fieldType: 'textarea',
        helpText: '如使用干投、桶陈、混合发酵等工艺，请描述对风味有影响的部分。',
        options: [],
        required: false,
        visibleToJudges: true,
        sortOrder: 0,
      },
      {
        fieldKey: 'flavorAdditions',
        fieldLabel: '增味原料',
        fieldType: 'multi_select',
        helpText: '仅选择会影响评审判断的原料。',
        options: ['无', '水果', '咖啡', '茶', '香料', '木桶', '蜂蜜', '其他'],
        required: false,
        visibleToJudges: true,
        sortOrder: 1,
      },
      {
        fieldKey: 'packageSpec',
        fieldLabel: '送样包装规格',
        fieldType: 'text',
        helpText: '填写瓶装或罐装规格，便于主办方收样核对。',
        options: [],
        required: true,
        visibleToJudges: false,
        sortOrder: 2,
      },
    ],
    summary: {
      submitted: 4,
      pendingPayment: 1,
      paid: 3,
      stored: 2,
      result: 1,
    },
    timeline: [
      { label: '开放报名', date: '2026-05-01', done: true },
      { label: '报名截止', date: '2026-07-20', active: true },
      { label: '酒样入库', date: '2026-08-01' },
      { label: '现场评审', date: '2026-08-18' },
      { label: '结果发布', date: '待确认' },
    ],
    actionLabel: '查看参赛进度',
  },
  {
    id: 'saison-2026',
    name: '2026 South China Saison Invitational',
    shortName: 'SC-2026',
    status: 'REGISTRATION_OPEN',
    stage: '报名中',
    date: '2026-09-12',
    registrationDeadline: '2026-08-10 18:00',
    entryFee: 159,
    venue: '广州番禺啤酒实验场',
    city: '广东 广州',
    organizer: '南中国赛松邀请赛组委会',
    description: '聚焦赛松、农舍、野菌与本地原料表达的小型邀请赛，适合提交实验批次和季节限定款。',
    audience: '适合提交赛松、农舍、混合发酵和本地原料表达明确的酒款。',
    sampleRequirement: '每款酒请准备 3 瓶或 3 罐，建议随箱附上参赛编号清单。',
    sampleDeadline: '2026-08-25 18:00',
    sampleAddress: '广东省广州市番禺区啤酒实验场赛事收样台',
    awardNote: '按专项组别评出奖项，结果发布后开放厂商反馈。',
    categories: ['经典赛松', '果味农舍', '野菌混酿'],
    styleOptions: ['Saison', 'Biere de Garde', 'Mixed Fermentation', 'Fruit Saison'],
    entryFields: [
      {
        fieldKey: 'yeastSource',
        fieldLabel: '酵母来源',
        fieldType: 'select',
        helpText: '选择主要发酵来源，评审会据此理解风味背景。',
        options: ['商业酵母', '混合菌', '野菌采集', '酒厂自养菌株'],
        required: true,
        visibleToJudges: true,
        sortOrder: 0,
      },
      {
        fieldKey: 'localMaterialNote',
        fieldLabel: '本地原料说明',
        fieldType: 'textarea',
        helpText: '描述本地原料和加入阶段，避免写厂牌或联系人。',
        options: [],
        required: false,
        visibleToJudges: true,
        sortOrder: 1,
      },
      {
        fieldKey: 'sampleBatch',
        fieldLabel: '送样批次',
        fieldType: 'text',
        helpText: '填写厂内批次号，供主办方和厂商核对。',
        options: [],
        required: false,
        visibleToJudges: false,
        sortOrder: 2,
      },
    ],
    summary: {
      submitted: 0,
      pendingPayment: 0,
      paid: 0,
      stored: 0,
      result: 0,
    },
    timeline: [
      { label: '开放报名', date: '2026-06-15', done: true },
      { label: '报名截止', date: '2026-08-10', active: true },
      { label: '酒样入库', date: '2026-08-25' },
      { label: '现场评审', date: '2026-09-12' },
      { label: '结果发布', date: '待确认' },
    ],
    actionLabel: '提交参赛酒款',
  },
  {
    id: 'winter-2025',
    name: '2025 Barrel & Winter Beer Cup',
    shortName: 'BW-2025',
    status: 'PUBLISHED',
    stage: '结果已发布',
    date: '2025-12-06',
    registrationDeadline: '2025-10-31 18:00',
    entryFee: 229,
    venue: '佛山创意产业园',
    city: '广东 佛山',
    organizer: 'Barrel & Winter Beer Cup 组委会',
    description: '冬季烈性啤酒、木桶熟成与甜点风味专项赛事，当前仅开放历史结果查看。',
    audience: '适合木桶熟成、冬季烈性和甜点风味酒款。',
    sampleRequirement: '历史赛事已结束，不再接收酒样。',
    sampleDeadline: '2025-11-20 18:00',
    sampleAddress: '佛山创意产业园赛事中心',
    awardNote: '历史结果已发布，可登录后查看本厂牌参赛反馈。',
    categories: ['木桶熟成', '冬季烈性啤酒', '甜点世涛'],
    styleOptions: ['Barrel Aged Stout', 'Old Ale', 'Strong Ale'],
    entryFields: [
      {
        fieldKey: 'barrelType',
        fieldLabel: '桶型',
        fieldType: 'select',
        helpText: '选择主要熟成容器。',
        options: ['波本桶', '威士忌桶', '葡萄酒桶', '朗姆桶', '无桶陈', '其他'],
        required: false,
        visibleToJudges: true,
        sortOrder: 0,
      },
      {
        fieldKey: 'agingMonths',
        fieldLabel: '熟成时长（月）',
        fieldType: 'number',
        helpText: '填写整数月数。',
        options: [],
        required: false,
        visibleToJudges: true,
        sortOrder: 1,
      },
    ],
    summary: {
      submitted: 1,
      pendingPayment: 0,
      paid: 1,
      stored: 1,
      result: 1,
    },
    timeline: [
      { label: '开放报名', date: '2025-09-12', done: true },
      { label: '报名截止', date: '2025-10-31', done: true },
      { label: '酒样入库', date: '2025-11-20', done: true },
      { label: '现场评审', date: '2025-12-06', done: true },
      { label: '结果发布', date: '2025-12-20', done: true },
    ],
    actionLabel: '查看历史结果',
  },
]

export const activeCompetition = competitions[0]

export const statusMeta = {
  PENDING_PAYMENT: { label: '待付款', tone: 'amber' },
  REGISTERED: { label: '报名成功', tone: 'green' },
  STORED: { label: '已入库', tone: 'blue' },
  RESULT_PUBLISHED: { label: '结果已出', tone: 'gold' },
  CANCELED: { label: '已取消', tone: 'muted' },
}

export const entries = [
  {
    id: 1,
    competitionId: 'bc-2026',
    uuid: 'BC-2026-IPA-0007',
    shortCode: 'A7K4',
    name: '松针海岸 West Coast IPA',
    categoryName: '美式 IPA',
    style: 'West Coast IPA',
    abv: '6.8%',
    ibu: 68,
    status: 'STORED',
    paymentStatus: 'PAID',
    fee: 199,
    submittedAt: '2026-05-12 14:22',
    paidAt: '2026-05-12 14:36',
    storedAt: '2026-05-26 10:18',
    description: '酒体清爽干净，使用 Columbus、Centennial 与 Simcoe 干投，突出松脂、葡萄柚皮和轻微草本香气。',
    extraFields: [
      { label: '特殊工艺', value: '低温长时间发酵，二次干投 12g/L' },
      { label: '增味原料', value: '无' },
    ],
    award: null,
    finalScore: null,
    comments: [],
  },
  {
    id: 2,
    competitionId: 'bc-2026',
    uuid: 'BC-2026-SOUR-0012',
    shortCode: 'R2M9',
    name: '荔枝玫瑰 Gose',
    categoryName: '果味酸啤',
    style: 'Gose',
    abv: '4.5%',
    ibu: 9,
    status: 'RESULT_PUBLISHED',
    paymentStatus: 'PAID',
    fee: 199,
    submittedAt: '2026-05-14 11:08',
    paidAt: '2026-05-14 11:20',
    storedAt: '2026-05-27 16:44',
    description: '轻盐感酸啤，加入广东荔枝汁与少量玫瑰花水，香气明亮，酸度柔和。',
    extraFields: [
      { label: '特殊工艺', value: '乳酸菌 kettle sour，冷端加入果汁' },
      { label: '增味原料', value: '荔枝汁、玫瑰花水、海盐' },
    ],
    award: '银奖',
    finalScore: 43.5,
    groupTotal: 28,
    captainComment: '香气表达完整，荔枝辨识度高，酸度与盐感平衡。后段玫瑰略显突出，整体仍有很好的完成度和记忆点。',
    comments: [
      { judge: '专业评审 A', aroma: 10, appearance: 3, flavor: 17, mouthfeel: 4, overall: 8.5, total: 42.5, text: '果香自然，酸度干净，收口略甜。' },
      { judge: '跨界评审 B', aroma: 13, appearance: 9, flavor: 14, mouthfeel: 7, overall: 43, total: 43, text: '很适合夏天饮用，花香有辨识度。' },
    ],
  },
  {
    id: 3,
    competitionId: 'bc-2026',
    uuid: 'BC-2026-STOUT-0021',
    shortCode: 'S8P1',
    name: '黑曜可可 Imperial Stout',
    categoryName: '深色烈性啤酒',
    style: 'Imperial Stout',
    abv: '10.2%',
    ibu: 42,
    status: 'REGISTERED',
    paymentStatus: 'PAID',
    fee: 199,
    submittedAt: '2026-05-18 20:10',
    paidAt: '2026-05-18 20:16',
    storedAt: null,
    description: '高酒精度世涛，烘烤麦芽、黑巧克力与咖啡风味明显，酒体厚实。',
    extraFields: [
      { label: '特殊工艺', value: '加入可可碎熟成 21 天' },
      { label: '增味原料', value: '厄瓜多尔可可碎、马达加斯加香草荚' },
    ],
    award: null,
    finalScore: null,
    comments: [],
  },
  {
    id: 4,
    competitionId: 'bc-2026',
    uuid: 'BC-2026-LAGER-0030',
    shortCode: 'L5H6',
    name: '白瓷 Helles',
    categoryName: '拉格',
    style: 'Munich Helles',
    abv: '5.0%',
    ibu: 19,
    status: 'PENDING_PAYMENT',
    paymentStatus: 'UNPAID',
    fee: 199,
    submittedAt: '2026-05-21 09:35',
    paidAt: null,
    storedAt: null,
    description: '淡色拉格，麦芽香干净柔和，苦度低，突出饼干、蜂蜜和细腻收口。',
    extraFields: [
      { label: '特殊工艺', value: '低温 lagering 45 天' },
      { label: '增味原料', value: '无' },
    ],
    award: null,
    finalScore: null,
    comments: [],
  },
]

export const competitionOptions = competitions.map((competition) => competition.name)

export const categoryOptions = ['美式 IPA', '果味酸啤', '深色烈性啤酒', '拉格', '赛松 / 农舍']

export const styleOptions = ['West Coast IPA', 'Hazy IPA', 'Gose', 'Imperial Stout', 'Munich Helles', 'Saison']

export const deliveryAddress = {
  receiver: '林启航',
  phone: '13800000001',
  region: '广东省 深圳市 南山区',
  detail: '蛇口街道海湾路 18 号山雾麦芽工坊',
}
