package com.beercompetition.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.beercompetition.common.context.BaseContext;
import com.beercompetition.common.exception.BaseException;
import com.beercompetition.common.exception.ResourceNotFoundException;
import com.beercompetition.common.util.PiiService;
import com.beercompetition.mapper.CompetitionMapper;
import com.beercompetition.mapper.BeerEntryMapper;
import com.beercompetition.mapper.AdminOperationLogMapper;
import com.beercompetition.mapper.JudgeAccountMapper;
import com.beercompetition.mapper.JudgeAssignmentMapper;
import com.beercompetition.mapper.JudgeRecruitmentApplicationMapper;
import com.beercompetition.mapper.JudgeRecruitmentMapper;
import com.beercompetition.pojo.dto.JudgeRecruitmentApplicationRequest;
import com.beercompetition.pojo.dto.JudgeRecruitmentRequest;
import com.beercompetition.pojo.dto.JudgeRecruitmentReviewRequest;
import com.beercompetition.pojo.enums.JudgeAccountStatus;
import com.beercompetition.pojo.po.Competition;
import com.beercompetition.pojo.po.JudgeAccount;
import com.beercompetition.pojo.po.JudgeAssignment;
import com.beercompetition.pojo.po.JudgeRecruitment;
import com.beercompetition.pojo.po.JudgeRecruitmentApplication;
import com.beercompetition.pojo.po.AdminOperationLog;
import com.beercompetition.pojo.vo.JudgeRecruitmentApplicationVO;
import com.beercompetition.pojo.vo.JudgeRecruitmentVO;
import com.beercompetition.judging.access.JudgeAccessService;
import com.beercompetition.service.JudgeRecruitmentService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Service @RequiredArgsConstructor
public class JudgeRecruitmentServiceImpl implements JudgeRecruitmentService {
 private final JudgeRecruitmentMapper recruitmentMapper; private final JudgeRecruitmentApplicationMapper applicationMapper;
 private final AdminOperationLogMapper adminOperationLogMapper;
 private final CompetitionMapper competitionMapper; private final JudgeAccountMapper judgeAccountMapper; private final JudgeAssignmentMapper assignmentMapper;
 private final BeerEntryMapper beerEntryMapper;
 private final JudgeAccessService judgeAccessService; private final PiiService piiService;
 private String pid(String p){return p+UUID.randomUUID().toString().replace("-","").substring(0,12).toUpperCase();}
 private JudgeRecruitment req(Long id){JudgeRecruitment r=recruitmentMapper.selectById(id);if(r==null)throw new ResourceNotFoundException("招募不存在");return r;}
 private Competition comp(Long id){Competition c=competitionMapper.selectById(id);if(c==null)throw new ResourceNotFoundException("比赛不存在");return c;}
 private void validate(JudgeRecruitmentRequest q){if(q.getRecruitmentDeadline().isBefore(q.getRecruitmentStart()))throw new BaseException("截止时间不能早于开始时间");}
 @Override public List<JudgeRecruitmentVO> adminList(String status,String keyword){return recruitmentMapper.selectList(new LambdaQueryWrapper<JudgeRecruitment>().eq(StringUtils.hasText(status),JudgeRecruitment::getStatus,status).orderByDesc(JudgeRecruitment::getCreateTime)).stream().filter(r->accessible(r.getCompetitionId())).filter(r->!StringUtils.hasText(keyword)||match(comp(r.getCompetitionId()),keyword)).map(this::toVO).toList();}
 private boolean accessible(Long competitionId){try{judgeAccessService.requireCompetitionAccess(competitionId);return true;}catch(RuntimeException e){return false;}}
 private boolean match(Competition c,String k){String x=k.toLowerCase();return String.valueOf(c.getName()).toLowerCase().contains(x)||String.valueOf(c.getCode()).toLowerCase().contains(x);}
 @Override public JudgeRecruitmentVO adminGet(Long id){JudgeRecruitment r=req(id);judgeAccessService.requireCompetitionAccess(r.getCompetitionId());return toVO(r);}
 @Override @Transactional public JudgeRecruitmentVO save(JudgeRecruitmentRequest q,Long id){validate(q);judgeAccessService.requireCompetitionAccess(q.getCompetitionId());comp(q.getCompetitionId());JudgeRecruitment r;if(id==null){if(recruitmentMapper.selectCount(new LambdaQueryWrapper<JudgeRecruitment>().eq(JudgeRecruitment::getCompetitionId,q.getCompetitionId()))>0)throw new BaseException("该比赛已有裁判招募");r=new JudgeRecruitment();r.setPublicId(pid("JR"));r.setCompetitionId(q.getCompetitionId());r.setStatus("DRAFT");}else{r=req(id);judgeAccessService.requireCompetitionAccess(r.getCompetitionId());if(!r.getCompetitionId().equals(q.getCompetitionId()))throw new BaseException("招募对应的比赛不能修改");if(!"DRAFT".equals(r.getStatus()))throw new BaseException("招募发布后不能编辑");}r.setRecruitmentStart(q.getRecruitmentStart());r.setRecruitmentDeadline(q.getRecruitmentDeadline());r.setVenue(q.getVenue().trim());r.setAddress(q.getAddress());r.setDescription(q.getDescription());r.setRequirements(q.getRequirements());r.setExpectedCount(q.getExpectedCount());if(id==null)recruitmentMapper.insert(r);else recruitmentMapper.updateById(r);log(id==null?"JUDGE_RECRUITMENT_CREATE":"JUDGE_RECRUITMENT_UPDATE",r.getPublicId(),id==null?"创建裁判招募":"更新裁判招募");return toVO(r);}
 @Override @Transactional public JudgeRecruitmentVO publish(Long id){JudgeRecruitment r=req(id);judgeAccessService.requireCompetitionAccess(r.getCompetitionId());if(r.getRecruitmentDeadline().isBefore(LocalDateTime.now()))throw new BaseException("招募截止时间已过");r.setStatus("OPEN");recruitmentMapper.updateById(r);log("JUDGE_RECRUITMENT_PUBLISH",r.getPublicId(),"发布裁判招募");return toVO(r);}
 @Override @Transactional public JudgeRecruitmentVO close(Long id){JudgeRecruitment r=req(id);judgeAccessService.requireCompetitionAccess(r.getCompetitionId());r.setStatus("CLOSED");r.setClosedTime(LocalDateTime.now());recruitmentMapper.updateById(r);log("JUDGE_RECRUITMENT_CLOSE",r.getPublicId(),"关闭裁判招募");return toVO(r);}
 @Override @Transactional public JudgeRecruitmentVO reopen(Long id){JudgeRecruitment r=req(id);judgeAccessService.requireCompetitionAccess(r.getCompetitionId());if(beerEntryMapper.countPublishedResults(r.getCompetitionId())>0)throw new BaseException("比赛结果已发布，不能再开放");r.setStatus("OPEN");r.setReopenedTime(LocalDateTime.now());r.setClosedTime(null);recruitmentMapper.updateById(r);log("JUDGE_RECRUITMENT_REOPEN",r.getPublicId(),"再开放裁判招募");return toVO(r);}
 @Override public List<JudgeRecruitmentApplicationVO> applications(Long id,String status,String keyword){JudgeRecruitment r=req(id);judgeAccessService.requireCompetitionAccess(r.getCompetitionId());return applicationMapper.selectList(new LambdaQueryWrapper<JudgeRecruitmentApplication>().eq(JudgeRecruitmentApplication::getRecruitmentId,id).eq(StringUtils.hasText(status),JudgeRecruitmentApplication::getStatus,status).orderByDesc(JudgeRecruitmentApplication::getCreateTime)).stream().map(this::toAppVO).filter(a->!StringUtils.hasText(keyword)||String.valueOf(a.getJudgeName()).contains(keyword)||String.valueOf(a.getQualification()).contains(keyword)).toList();}
 @Override @Transactional public JudgeRecruitmentApplicationVO review(Long aid,JudgeRecruitmentReviewRequest q){JudgeRecruitmentApplication a=applicationMapper.selectById(aid);if(a==null)throw new ResourceNotFoundException("报名不存在");JudgeRecruitment r=req(a.getRecruitmentId());judgeAccessService.requireCompetitionAccess(r.getCompetitionId());if(!List.of("ACCEPTED","REJECTED").contains(q.getStatus()))throw new BaseException("审核状态无效");if(!List.of("APPLIED","ACCEPTED","REJECTED").contains(a.getStatus()))throw new BaseException("当前状态不能修改");if("ACCEPTED".equals(a.getStatus())&&"REJECTED".equals(q.getStatus())&&assignmentMapper.selectCount(new LambdaQueryWrapper<JudgeAssignment>().eq(JudgeAssignment::getCompetitionId,r.getCompetitionId()).eq(JudgeAssignment::getJudgeAccountId,a.getJudgeAccountId()))>0)throw new BaseException("已分配评审桌，不能取消录用");a.setStatus(q.getStatus());a.setReviewRemark(q.getReviewRemark());a.setProcessedBy(BaseContext.getCurrentId());a.setProcessedTime(LocalDateTime.now());applicationMapper.updateById(a);log("JUDGE_RECRUITMENT_APPLICATION_REVIEW",a.getPublicId(),"报名状态改为"+q.getStatus());return toAppVO(a);}
 @Override public List<JudgeRecruitmentVO> publicList(){LocalDateTime now=LocalDateTime.now();return recruitmentMapper.selectList(new LambdaQueryWrapper<JudgeRecruitment>().eq(JudgeRecruitment::getStatus,"OPEN").le(JudgeRecruitment::getRecruitmentStart,now).and(w->w.ge(JudgeRecruitment::getRecruitmentDeadline,now).or().isNotNull(JudgeRecruitment::getReopenedTime)).orderByAsc(JudgeRecruitment::getRecruitmentDeadline)).stream().map(this::publicVO).toList();}
 @Override public JudgeRecruitmentVO publicGet(Long id){JudgeRecruitment r=req(id);if(!"OPEN".equals(r.getStatus())||(r.getRecruitmentDeadline().isBefore(LocalDateTime.now())&&r.getReopenedTime()==null))throw new BaseException("招募已关闭");return publicVO(r);}
 @Override public List<JudgeRecruitmentVO> myApplications(){Long jid=BaseContext.getCurrentId();return applicationMapper.selectList(new LambdaQueryWrapper<JudgeRecruitmentApplication>().eq(JudgeRecruitmentApplication::getJudgeAccountId,jid).orderByDesc(JudgeRecruitmentApplication::getCreateTime)).stream().map(a->{JudgeRecruitmentVO v=publicVO(req(a.getRecruitmentId()));v.setMyApplicationId(a.getId());v.setMyApplicationStatus(a.getStatus());v.setMyApplicationPublicId(a.getPublicId());v.setMyAvailabilityConfirmed(a.getAvailabilityConfirmed());v.setMyNote(a.getNote());v.setMyReviewRemark(a.getReviewRemark());return v;}).toList();}
 @Override @Transactional public JudgeRecruitmentApplicationVO apply(Long id,JudgeRecruitmentApplicationRequest q){JudgeAccount j=judgeAccountMapper.selectById(BaseContext.getCurrentId());if(j==null||JudgeAccountStatus.of(j.getStatus())!=JudgeAccountStatus.ACTIVE)throw new BaseException("账号未启用");if(!StringUtils.hasText(j.getName())||!StringUtils.hasText(j.getQualification()))throw new BaseException("请先完善评审姓名和资质资料");JudgeRecruitment r=req(id);if(!"OPEN".equals(r.getStatus())||(r.getRecruitmentDeadline().isBefore(LocalDateTime.now())&&r.getReopenedTime()==null))throw new BaseException("招募已关闭");if(!Boolean.TRUE.equals(q.getAvailabilityConfirmed()))throw new BaseException("请确认可以参加比赛日期");JudgeRecruitmentApplication a=applicationMapper.selectOne(new LambdaQueryWrapper<JudgeRecruitmentApplication>().eq(JudgeRecruitmentApplication::getRecruitmentId,id).eq(JudgeRecruitmentApplication::getJudgeAccountId,j.getId()));if(a!=null&&!"WITHDRAWN".equals(a.getStatus()))throw new BaseException("已报名该比赛");if(a==null){a=new JudgeRecruitmentApplication();a.setPublicId(pid("JRA"));a.setRecruitmentId(id);a.setJudgeAccountId(j.getId());}a.setAvailabilityConfirmed(true);a.setNote(q.getNote());a.setStatus("APPLIED");a.setWithdrawnTime(null);if(a.getId()==null)applicationMapper.insert(a);else applicationMapper.updateById(a);return toAppVO(a);}
 @Override @Transactional public JudgeRecruitmentApplicationVO updateApplication(Long aid,JudgeRecruitmentApplicationRequest q){if(!Boolean.TRUE.equals(q.getAvailabilityConfirmed()))throw new BaseException("请确认可以参加比赛日期");JudgeRecruitmentApplication a=applicationMapper.selectById(aid);if(a==null||!a.getJudgeAccountId().equals(BaseContext.getCurrentId()))throw new ResourceNotFoundException("报名不存在");if(!List.of("APPLIED","REJECTED").contains(a.getStatus()))throw new BaseException("当前状态不能修改报名");JudgeRecruitment r=req(a.getRecruitmentId());if(!"OPEN".equals(r.getStatus())||(r.getRecruitmentDeadline().isBefore(LocalDateTime.now())&&r.getReopenedTime()==null))throw new BaseException("招募已关闭");a.setAvailabilityConfirmed(true);a.setNote(q.getNote());a.setStatus("APPLIED");a.setReviewRemark(null);a.setProcessedBy(null);a.setProcessedTime(null);applicationMapper.updateById(a);return toAppVO(a);}
 @Override @Transactional public JudgeRecruitmentApplicationVO withdraw(Long aid){JudgeRecruitmentApplication a=applicationMapper.selectById(aid);if(a==null||!a.getJudgeAccountId().equals(BaseContext.getCurrentId()))throw new ResourceNotFoundException("报名不存在");if(!List.of("APPLIED","ACCEPTED").contains(a.getStatus()))throw new BaseException("当前状态不能取消报名");JudgeRecruitment r=req(a.getRecruitmentId());if(r.getRecruitmentDeadline().isBefore(LocalDateTime.now())&&r.getReopenedTime()==null)throw new BaseException("报名时间已截止，不能取消报名");if(assignmentMapper.selectCount(new LambdaQueryWrapper<JudgeAssignment>().eq(JudgeAssignment::getJudgeAccountId,a.getJudgeAccountId()).eq(JudgeAssignment::getCompetitionId,r.getCompetitionId()))>0)throw new BaseException("已分配评审桌，不能取消报名");a.setStatus("WITHDRAWN");a.setWithdrawnTime(LocalDateTime.now());applicationMapper.updateById(a);return toAppVO(a);}
 private JudgeRecruitmentVO toVO(JudgeRecruitment r){Competition c=comp(r.getCompetitionId());List<JudgeRecruitmentApplication> as=applicationMapper.selectList(new LambdaQueryWrapper<JudgeRecruitmentApplication>().eq(JudgeRecruitmentApplication::getRecruitmentId,r.getId()));Long jid=BaseContext.getCurrentId();JudgeRecruitmentApplication mine=as.stream().filter(a->a.getJudgeAccountId().equals(jid)).findFirst().orElse(null);return JudgeRecruitmentVO.builder().id(r.getId()).publicId(r.getPublicId()).competitionId(c.getId()).competitionCode(c.getCode()).competitionName(c.getName()).competitionDate(c.getCompetitionDate()).status(r.getStatus()).recruitmentStart(r.getRecruitmentStart()).recruitmentDeadline(r.getRecruitmentDeadline()).venue(r.getVenue()).address(r.getAddress()).description(r.getDescription()).requirements(r.getRequirements()).expectedCount(r.getExpectedCount()).applicationCount(as.size()).pendingCount((int)as.stream().filter(a->"APPLIED".equals(a.getStatus())).count()).acceptedCount((int)as.stream().filter(a->"ACCEPTED".equals(a.getStatus())).count()).myApplicationStatus(mine==null?null:mine.getStatus()).myApplicationPublicId(mine==null?null:mine.getPublicId()).build();}
 private JudgeRecruitmentVO publicVO(JudgeRecruitment r){JudgeRecruitmentVO v=toVO(r);v.setApplicationCount(null);v.setPendingCount(null);v.setAcceptedCount(null);v.setExpectedCount(null);return v;}
 private void log(String action,String target,String summary){if(BaseContext.getCurrentId()!=null)adminOperationLogMapper.insert(AdminOperationLog.builder().adminUserId(BaseContext.getCurrentId()).action(action).targetType("JUDGE_RECRUITMENT").targetPublicId(target).summary(summary).build());}
 private JudgeRecruitmentApplicationVO toAppVO(JudgeRecruitmentApplication a){JudgeAccount j=judgeAccountMapper.selectById(a.getJudgeAccountId());Competition c=comp(req(a.getRecruitmentId()).getCompetitionId());return JudgeRecruitmentApplicationVO.builder().id(a.getId()).publicId(a.getPublicId()).recruitmentId(a.getRecruitmentId()).competitionId(c.getId()).competitionName(c.getName()).competitionCode(c.getCode()).competitionDate(c.getCompetitionDate()).judgePublicId(j==null?null:j.getPublicId()).judgeName(j==null?null:j.getName()).maskedPhone(j==null?null:piiService.maskPhone(piiService.decrypt(j.getPhoneEnc()))).qualification(j==null?null:j.getQualification()).breweryConflictFlag(j!=null&&Boolean.TRUE.equals(j.getBreweryConflictFlag())).breweryConflictText(j==null?null:j.getBreweryConflictText()).status(a.getStatus()).availabilityConfirmed(a.getAvailabilityConfirmed()).note(a.getNote()).reviewRemark(a.getReviewRemark()).createTime(a.getCreateTime()).processedTime(a.getProcessedTime()).build();}
}


